### ISSUE TITLE
Update Ywallet-based sign tool

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/frost-zcash-demo#217]
The current sign tool is based on Ywallet and is in a branch in https://github.com/ZcashFoundation/zwallet. This is based on an old version of Ywallet.

This causes the following problems:

- We are using outdated versions of ECC crates
- Those crates have local changes that never were contributed upstream. It's best to coordinate with ECC so we don't need to maitain forks of the crates
- The tool is awkward to compile because it requires the entire zwallet repo due to how it's structured (patched versions of dependencies)
- The tool is awkward to use because the old ECC crates do not support Orchard-only UFVKs, which thus require generating a Sapling key which will never be used (and can lead to the user accidentally sending funds to the Sapling key which is not currently protected by FROST in the tool)

Ideally, we would like to:

- Update the code to use the latest ECC crates
- Refactor the code so that it generates a Orchard-only wallet does not require a Sapling key. This was blocked on ECC crates not supporting that since they didn't support Orchard at the time, so we need to check if that is now possible. This may also be blocked on whether Ywallet supports importing Orchard-only full viewing keys, need to check.
- Move the code out of zwallet repo and into this repo, either as a separate crate or integrated with the Coordinator?

This work will also help with:

- Mapping out the changes required to ECC crates so we can discuss them and hopefully get the changes upstream
- Better understanding the overall flow of the process
- Better understanding of the transaction plan format, which we would like to standardize at some point

**Comment by skyl** [comment]
I think maybe the FROST book ywallet demo doesn't work anymore related to this?

```
thread 'main' panicked at native/zcash-sync/src/main/sign.rs:79:83:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:        0x10501c2e7 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h31f9e6a79997ef5f
   1:        0x104ec2a8b - core::fmt::write::h85020c7a61eba8ce
   2:        0x104ff2062 - std::io::Write::write_fmt::hcc19df4fa4e73a55
   3:        0x10501df81 - std::sys_common::backtrace::print::h45d16fbbed4d1f36
   4:        0x10501d6c4 - std::panicking::default_hook::{{closure}}::h885e10af905b3914
   5:        0x10501f6b1 - std::panicking::rust_panic_with_hook::h9e15a0c845c470d6
   6:        0x10501e25a - std::panicking::begin_panic_handler::{{closure}}::h3cd5140e29c8cfc1
   7:        0x10501e1e9 - std::sys_common::backtrace::__rust_end_short_backtrace::h124259ee4cbc9197
   8:        0x10501e1d6 - _rust_begin_unwind
   9:        0x1051fdbb2 - core::panicking::panic_fmt::h9772381b80805b71
  10:        0x1051fdd54 - core::panicking::panic::h2a3e12572053020c
  11:        0x1051fe098 - core::option::unwrap_failed::hf02468572e4a732f
  12:        0x104e4208a - sign::main::ha5ae19589152b6df
  13:        0x104dc21b6 - std::sys_common::backtrace::__rust_begin_short_backtrace::h29c613b61e885081
  14:        0x104e45a9a - _main
  ```
  
  https://discord.com/channels/809218587167293450/1265705834608984064/1270526753986711636
