### ISSUE TITLE
Round 2: Serialize round 2 output in Participant CLI demo

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/frost-zcash-demo#23]

**Comment by natalieesk** [comment]
Commits incorrectly assigned to #20:

https://github.com/ZcashFoundation/frost-zcash-demo/commit/758df17b8e478eac6bffcb3efd3d07cdc8623ea2
https://github.com/ZcashFoundation/frost-zcash-demo/commit/78f3a7eaa71c6ad8df39ed586693ad173eac761e
https://github.com/ZcashFoundation/frost-zcash-demo/commit/b62085a667d3006a0303208d2a091e4f5580cd7f
https://github.com/ZcashFoundation/frost-zcash-demo/commit/fe7111ead28611665eeaad2a6be7b88a9db76863
https://github.com/ZcashFoundation/frost-zcash-demo/commit/3f89f74ba44b237e5926b7cc13acde9906a3fc53
https://github.com/ZcashFoundation/frost-zcash-demo/commit/7d1c5cd4e152e7024280f0487e455e4010c89e6d
