### ISSUE TITLE
Add frost-client support to trusted-dealer

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/frost-zcash-demo#306]
`trusted-dealer` currently writes keys to JSON files specified in the command line.

We want it to write it to the frost-client config file.

(One idea is to use `frost-client trusted-dealer` and refactor the existing code to support both the old and new approaches)

**Comment by mpguerra** [comment]
@conradoplg can this one be closed already?

**Comment by conradoplg** [comment]
Yep! Not sure why it was left open.
